apply plugin: 'com.android.application'

android {
    compileSdk 34
    defaultConfig {
        applicationId "com.anaghizdavat.activity"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 9
        versionName "1.0.5"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias 'keyactivitytime'
            keyPassword 'keyAc01'
            storeFile file('E:/Work/Ghizdavat/ActivityTime/ActivityTime/app/keyActivityTime.jks')
            storePassword 'keyAc01'
        }
    }

    buildTypes {
        release {
            minifyEnabled false // can't run because because firebase crashlytics
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    flavorDimensions = ["services"]
    productFlavors {
        gms {
            versionCode 9
            versionName "1.0.5"
            dimension "services"
        }
        hms {
            versionCode 10
            versionName "1.0.6"
            dimension "services"
        }
    }


    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    namespace 'com.anaghizdavat.activity'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'

    //google
    gmsImplementation 'com.google.android.gms:play-services-ads:23.4.0'
    gmsImplementation platform('com.google.firebase:firebase-bom:33.4.0')
    gmsImplementation 'com.google.firebase:firebase-analytics'
    gmsImplementation 'com.google.firebase:firebase-crashlytics'

    //huawei
    hmsImplementation 'com.huawei.agconnect:agconnect-core:1.4.1.300'
    hmsImplementation 'com.huawei.hms:hianalytics:5.0.0.300'
    hmsImplementation 'com.huawei.hms:dtm-api:4.0.0.300'
    hmsImplementation 'com.huawei.agconnect:agconnect-crash:1.4.1.300'

    //appsflyer
    implementation 'com.appsflyer:af-android-sdk:6.3.2'

    //calligraphy
    implementation 'uk.co.chrisjenx:calligraphy:2.3.0'

    //butter knife todo change with data binding
//    implementation 'com.jakewharton:butterknife:10.2.0'
//    annotationProcessor 'com.jakewharton:butterknife-compiler:10.2.0'

    //multidex
    implementation 'androidx.multidex:multidex:2.0.1'
}

if (getGradle().getStartParameter().getTaskRequests().toString().toLowerCase().contains("gms")) {
    apply plugin: 'com.google.gms.google-services'
    apply plugin: 'com.google.firebase.crashlytics'
} else {
    apply plugin: 'com.huawei.agconnect'
}
